apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  git:
    # Change this to point to your repo
    syncRepo: https://github.com/sekka1/gcp-anthos-config-sync-example
    # We recommend securing your source repository.
    # Other supported secretType: `ssh`, `cookiefile`, `token`, `gcenode`.
    secretType: none
    policyDir: /
    syncBranch: main
  sourceFormat: unstructured
